// Code generated by mockery v2.53.4. DO NOT EDIT.

// Regenerate this file using `make store-mocks`.

package mocks

import (
	model "github.com/mattermost/mattermost/server/public/model"
	request "github.com/mattermost/mattermost/server/public/shared/request"
	mock "github.com/stretchr/testify/mock"
)

// DirectMessageExceptionStore is an autogenerated mock type for the DirectMessageExceptionStore type
type DirectMessageExceptionStore struct {
	mock.Mock
}

// Delete provides a mock function with given fields: userID1, userID2
func (_m *DirectMessageExceptionStore) Delete(userID1 string, userID2 string) error {
	ret := _m.Called(userID1, userID2)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(userID1, userID2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with no fields
func (_m *DirectMessageExceptionStore) GetAll() ([]*model.DirectMessageException, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*model.DirectMessageException
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*model.DirectMessageException, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*model.DirectMessageException); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.DirectMessageException)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPartnersForUser provides a mock function with given fields: userID
func (_m *DirectMessageExceptionStore) GetPartnersForUser(userID string) ([]string, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetPartnersForUser")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsException provides a mock function with given fields: userID1, userID2
func (_m *DirectMessageExceptionStore) IsException(userID1 string, userID2 string) (bool, error) {
	ret := _m.Called(userID1, userID2)

	if len(ret) == 0 {
		panic("no return value specified for IsException")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (bool, error)); ok {
		return rf(userID1, userID2)
	}
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(userID1, userID2)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(userID1, userID2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: rctx, userID1, userID2, createdBy
func (_m *DirectMessageExceptionStore) Save(rctx request.CTX, userID1 string, userID2 string, createdBy string) error {
	ret := _m.Called(rctx, userID1, userID2, createdBy)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(request.CTX, string, string, string) error); ok {
		r0 = rf(rctx, userID1, userID2, createdBy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDirectMessageExceptionStore creates a new instance of DirectMessageExceptionStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDirectMessageExceptionStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *DirectMessageExceptionStore {
	mock := &DirectMessageExceptionStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
