// Code generated by mockery v2.53.4. DO NOT EDIT.

// Regenerate this file using `make store-mocks`.

package mocks

import (
	model "github.com/mattermost/mattermost/server/public/model"
	request "github.com/mattermost/mattermost/server/public/shared/request"
	mock "github.com/stretchr/testify/mock"
)

// OperationalTrackingGroupStore is an autogenerated mock type for the OperationalTrackingGroupStore type
type OperationalTrackingGroupStore struct {
	mock.Mock
}

// AddMember provides a mock function with given fields: rctx, groupID, userID, createdBy
func (_m *OperationalTrackingGroupStore) AddMember(rctx request.CTX, groupID string, userID string, createdBy string) error {
	ret := _m.Called(rctx, groupID, userID, createdBy)

	if len(ret) == 0 {
		panic("no return value specified for AddMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(request.CTX, string, string, string) error); ok {
		r0 = rf(rctx, groupID, userID, createdBy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: groupID
func (_m *OperationalTrackingGroupStore) Delete(groupID string) error {
	ret := _m.Called(groupID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(groupID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: groupID
func (_m *OperationalTrackingGroupStore) Get(groupID string) (*model.OperationalTrackingGroup, error) {
	ret := _m.Called(groupID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.OperationalTrackingGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*model.OperationalTrackingGroup, error)); ok {
		return rf(groupID)
	}
	if rf, ok := ret.Get(0).(func(string) *model.OperationalTrackingGroup); ok {
		r0 = rf(groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OperationalTrackingGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(groupID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetForTeam provides a mock function with given fields: teamID
func (_m *OperationalTrackingGroupStore) GetForTeam(teamID string) ([]*model.OperationalTrackingGroup, error) {
	ret := _m.Called(teamID)

	if len(ret) == 0 {
		panic("no return value specified for GetForTeam")
	}

	var r0 []*model.OperationalTrackingGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*model.OperationalTrackingGroup, error)); ok {
		return rf(teamID)
	}
	if rf, ok := ret.Get(0).(func(string) []*model.OperationalTrackingGroup); ok {
		r0 = rf(teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.OperationalTrackingGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(teamID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMembers provides a mock function with given fields: groupID
func (_m *OperationalTrackingGroupStore) GetMembers(groupID string) ([]*model.OperationalTrackingGroupMember, error) {
	ret := _m.Called(groupID)

	if len(ret) == 0 {
		panic("no return value specified for GetMembers")
	}

	var r0 []*model.OperationalTrackingGroupMember
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*model.OperationalTrackingGroupMember, error)); ok {
		return rf(groupID)
	}
	if rf, ok := ret.Get(0).(func(string) []*model.OperationalTrackingGroupMember); ok {
		r0 = rf(groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.OperationalTrackingGroupMember)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(groupID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveMember provides a mock function with given fields: groupID, userID
func (_m *OperationalTrackingGroupStore) RemoveMember(groupID string, userID string) error {
	ret := _m.Called(groupID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(groupID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Save provides a mock function with given fields: rctx, group
func (_m *OperationalTrackingGroupStore) Save(rctx request.CTX, group *model.OperationalTrackingGroup) (*model.OperationalTrackingGroup, error) {
	ret := _m.Called(rctx, group)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *model.OperationalTrackingGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(request.CTX, *model.OperationalTrackingGroup) (*model.OperationalTrackingGroup, error)); ok {
		return rf(rctx, group)
	}
	if rf, ok := ret.Get(0).(func(request.CTX, *model.OperationalTrackingGroup) *model.OperationalTrackingGroup); ok {
		r0 = rf(rctx, group)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OperationalTrackingGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(request.CTX, *model.OperationalTrackingGroup) error); ok {
		r1 = rf(rctx, group)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateName provides a mock function with given fields: groupID, name
func (_m *OperationalTrackingGroupStore) UpdateName(groupID string, name string) error {
	ret := _m.Called(groupID, name)

	if len(ret) == 0 {
		panic("no return value specified for UpdateName")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(groupID, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewOperationalTrackingGroupStore creates a new instance of OperationalTrackingGroupStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOperationalTrackingGroupStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *OperationalTrackingGroupStore {
	mock := &OperationalTrackingGroupStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
