// Code generated by mockery v2.53.4. DO NOT EDIT.

// Regenerate this file using `make store-mocks`.

package mocks

import (
	request "github.com/mattermost/mattermost/server/public/shared/request"
	mock "github.com/stretchr/testify/mock"
)

// TeamOrganizationMemberStore is an autogenerated mock type for the TeamOrganizationMemberStore type
type TeamOrganizationMemberStore struct {
	mock.Mock
}

// Delete provides a mock function with given fields: teamID, userID
func (_m *TeamOrganizationMemberStore) Delete(teamID string, userID string) error {
	ret := _m.Called(teamID, userID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(teamID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetForTeam provides a mock function with given fields: teamID
func (_m *TeamOrganizationMemberStore) GetForTeam(teamID string) ([]string, error) {
	ret := _m.Called(teamID)

	if len(ret) == 0 {
		panic("no return value specified for GetForTeam")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return rf(teamID)
	}
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(teamID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetForUser provides a mock function with given fields: userID
func (_m *TeamOrganizationMemberStore) GetForUser(userID string) ([]string, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetForUser")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsOrgMember provides a mock function with given fields: teamID, userID
func (_m *TeamOrganizationMemberStore) IsOrgMember(teamID string, userID string) (bool, error) {
	ret := _m.Called(teamID, userID)

	if len(ret) == 0 {
		panic("no return value specified for IsOrgMember")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (bool, error)); ok {
		return rf(teamID, userID)
	}
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(teamID, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(teamID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: rctx, teamID, userID, createdBy
func (_m *TeamOrganizationMemberStore) Save(rctx request.CTX, teamID string, userID string, createdBy string) error {
	ret := _m.Called(rctx, teamID, userID, createdBy)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(request.CTX, string, string, string) error); ok {
		r0 = rf(rctx, teamID, userID, createdBy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTeamOrganizationMemberStore creates a new instance of TeamOrganizationMemberStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTeamOrganizationMemberStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *TeamOrganizationMemberStore {
	mock := &TeamOrganizationMemberStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
