// Code generated by mockery v2.53.4. DO NOT EDIT.

// Regenerate this file using `make store-mocks`.

package mocks

import (
	model "github.com/mattermost/mattermost/server/public/model"
	mock "github.com/stretchr/testify/mock"
)

// WelcomeBotReportStore is an autogenerated mock type for the WelcomeBotReportStore type
type WelcomeBotReportStore struct {
	mock.Mock
}

// ClearPending provides a mock function with given fields: userID
func (_m *WelcomeBotReportStore) ClearPending(userID string) error {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for ClearPending")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetPage provides a mock function with given fields: page, perPage, onlyUnresolved
func (_m *WelcomeBotReportStore) GetPage(page int, perPage int, onlyUnresolved bool) ([]*model.WelcomeBotReport, error) {
	ret := _m.Called(page, perPage, onlyUnresolved)

	if len(ret) == 0 {
		panic("no return value specified for GetPage")
	}

	var r0 []*model.WelcomeBotReport
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int, bool) ([]*model.WelcomeBotReport, error)); ok {
		return rf(page, perPage, onlyUnresolved)
	}
	if rf, ok := ret.Get(0).(func(int, int, bool) []*model.WelcomeBotReport); ok {
		r0 = rf(page, perPage, onlyUnresolved)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.WelcomeBotReport)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, bool) error); ok {
		r1 = rf(page, perPage, onlyUnresolved)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsPending provides a mock function with given fields: userID
func (_m *WelcomeBotReportStore) IsPending(userID string) (bool, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for IsPending")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Resolve provides a mock function with given fields: reportID, resolvedBy, resolvedAt
func (_m *WelcomeBotReportStore) Resolve(reportID string, resolvedBy string, resolvedAt int64) error {
	ret := _m.Called(reportID, resolvedBy, resolvedAt)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, int64) error); ok {
		r0 = rf(reportID, resolvedBy, resolvedAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Save provides a mock function with given fields: report
func (_m *WelcomeBotReportStore) Save(report *model.WelcomeBotReport) (*model.WelcomeBotReport, error) {
	ret := _m.Called(report)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *model.WelcomeBotReport
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.WelcomeBotReport) (*model.WelcomeBotReport, error)); ok {
		return rf(report)
	}
	if rf, ok := ret.Get(0).(func(*model.WelcomeBotReport) *model.WelcomeBotReport); ok {
		r0 = rf(report)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.WelcomeBotReport)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.WelcomeBotReport) error); ok {
		r1 = rf(report)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetPending provides a mock function with given fields: userID, createAt
func (_m *WelcomeBotReportStore) SetPending(userID string, createAt int64) error {
	ret := _m.Called(userID, createAt)

	if len(ret) == 0 {
		panic("no return value specified for SetPending")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int64) error); ok {
		r0 = rf(userID, createAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewWelcomeBotReportStore creates a new instance of WelcomeBotReportStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWelcomeBotReportStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *WelcomeBotReportStore {
	mock := &WelcomeBotReportStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
